server:
  port: 8099
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security_vue?serverTimezone=GMT%2B8
  redis:
    host: 192.168.43.226
    port: 6379

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
